apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  labels:
    app: {{ .Values.mongodb.name }}
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.mongodb.user }}
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.mongodb.rootPassword }}
  MONGO_INITDB_DATABASE: {{ .Values.mongodb.database }}
